version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.1
    - 2.18.2
    - 2.18.3
    - 2.18.4
    - 2.18.5
  - dependency-name: symfony/http-client
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/process
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.2.0
